### PR TITLE
Handful of small cleanups/fixes

### PR DESCRIPTION
**Pull request by jcalvinowens**
Hi @kernelslacker and @davide125 ,

I saw this repo show up, thought I'd pitch in by fixing a few silly things I did in 2016. I think the 3rd patch may fix the open issue about endianness (I didn't see it until I was about to submit this). The srcaddr_order/thread_order thing is very confusing... I might send along another PR to clean it up in a week or two.

All the best,
Calvin

### CODE REVIEW

**Comment by kernelslacker** [comment]
lgtm from a quick scan, I'll give it another once-over tomorrow, and then figure out what acl I need to be in merge this.

good to hear from you!

**Comment by davide125** [comment]
Thanks Calvin, it's great to hear from you! We'll get this reviewed and imported tomorrow.

**Comment by davide125** [comment]
I can confirm this fixes the netconsblaster build issue on s390x in #3: https://koji.fedoraproject.org/koji/taskinfo?taskID=78526108

**Comment by davide125** [comment]
Sorry for squashing these but apparently that's how our import automation works :-(

**Pull request closed without merging**
